"""Reference data that every environment needs."""

# (slug, English name, Arabic name). Technology names stay in their original form,
# which is how Arabic-speaking developers write them.
INTERESTS = [
    ("javascript", "JavaScript", "JavaScript"),
    ("typescript", "TypeScript", "TypeScript"),
    ("python", "Python", "Python"),
    ("cpp", "C++", "C++"),
    ("rust", "Rust", "Rust"),
    ("go", "Go", "Go"),
    ("java", "Java", "Java"),
    ("csharp", "C#", "C#"),
    ("react", "React", "React"),
    ("vue", "Vue", "Vue"),
    ("angular", "Angular", "Angular"),
    ("nodejs", "Node.js", "Node.js"),
    ("fastapi", "FastAPI", "FastAPI"),
    ("django", "Django", "Django"),
    ("ai", "AI", "الذكاء الاصطناعي"),
    ("machine-learning", "Machine Learning", "تعلّم الآلة"),
    ("cybersecurity", "Cybersecurity", "الأمن السيبراني"),
    ("linux", "Linux", "Linux"),
    ("devops", "DevOps", "DevOps"),
    ("cloud", "Cloud", "الحوسبة السحابية"),
    ("databases", "Databases", "قواعد البيانات"),
    ("game-development", "Game Development", "تطوير الألعاب"),
    ("mobile-development", "Mobile Development", "تطوير تطبيقات الجوال"),
    ("ui-ux", "UI/UX", "تصميم الواجهات UI/UX"),
    ("open-source", "Open Source", "المصادر المفتوحة"),
]

# House ads: ArabDev promoting its own features. They are labelled as ads in the UI,
# point inside the product (or to ArabDev's own wiki), and never pretend to be a third-party brand.
HOUSE_ADS = [
    {
        "sponsor": "ArabDev",
        "title": "شارك مشروعك مفتوح المصدر",
        "body": "اكتب منشورًا عن مشروعك: ما المشكلة التي يحلها، وكيف يمكن للآخرين المساهمة فيه.",
        "cta_label": "اكتب منشورًا",
        "target_url": "/create",
        "placement": "all",
        "language": "ar",
    },
    {
        "sponsor": "ArabDev",
        "title": "أكمل ملفك الشخصي",
        "body": "صورة ونبذة قصيرة واهتمامات واضحة تساعد المطورين على العثور عليك ومتابعتك.",
        "cta_label": "تعديل الملف",
        "target_url": "/profile/edit",
        "placement": "all",
        "language": "ar",
    },
    {
        "sponsor": "ArabDev",
        "title": "اكتشف الوسوم الرائجة",
        "body": "تابع ما يكتب عنه المجتمع هذا الأسبوع، من Rust إلى الأمن السيبراني.",
        "cta_label": "استكشف",
        "target_url": "/explore",
        "placement": "all",
        "language": "ar",
    },
    {
        "sponsor": "ArabDev",
        "title": "ادعم ArabDev وكن راعيًا",
        "body": "تواصل مع آلاف المطورين العرب بإعلانات واضحة تحترم الخصوصية. راسلنا على hi@arabdev.site.",
        "cta_label": "كيف ترعى ArabDev",
        "target_url": "https://wiki.arabdev.site/ar/#contact-hello",
        "placement": "all",
        "language": "ar",
    },
    {
        "sponsor": "ArabDev",
        "title": "Share your open-source project",
        "body": "Write a post about what you're building, the problem it solves and how people can contribute.",
        "cta_label": "Write a post",
        "target_url": "/create",
        "placement": "all",
        "language": "en",
    },
    {
        "sponsor": "ArabDev",
        "title": "Complete your profile",
        "body": "A photo, a short bio and clear interests help other developers find and follow you.",
        "cta_label": "Edit profile",
        "target_url": "/profile/edit",
        "placement": "all",
        "language": "en",
    },
    {
        "sponsor": "ArabDev",
        "title": "See what's trending",
        "body": "Catch up on what the community is writing about this week, from Rust to security.",
        "cta_label": "Explore",
        "target_url": "/explore",
        "placement": "all",
        "language": "en",
    },
    {
        "sponsor": "ArabDev",
        "title": "Sponsor ArabDev",
        "body": "Reach Arabic-speaking developers with clearly labelled, privacy-respecting ads. Write to hi@arabdev.site.",
        "cta_label": "How to sponsor",
        "target_url": "https://wiki.arabdev.site/en/#contact-hello",
        "placement": "all",
        "language": "en",
    },
]
